language: node_js
node_js:
- '0.10'
before_script:
- chmod +x .travis/after_success.sh
env:
  global:
  - REPO="git@github.com:g0v/closelyheld-gitbook"
  - secure: h6YrS+Q4sQrG3OXmaFlbtVu0dmH2S66lXZ3Rl68t3JjWOgUl9DQ/tRgTC87VH9Jee/+iHigYasIEpNUgzNs5MegWCMQkRYKCCU399s+PYL6RG5tMQuF212kf6o+F6S6f3S2dcEAgrCQVvusyUDJ1BiGgWwhFiAV2xG5Espp/yJk=
after_success: ".travis/after_success.sh"
